iversion: "3.7"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - 8000:8000
  lambdas:
    build:
      context: ./btc_predictor
      dockerfile: Dockerfile
    image: btc_predictor:local
    volumnes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      sam local start-lambda --host 0.0.0.0 --port 3001
    networks:
      - lambda

