version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BTCPredictorApi"
s3_bucket = "btc-dash"
s3_prefix = "aws-sam/BTCPredictorApi"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["BTCPredictorAPI={AWS_ACCOUNT_PLACEHOLDER}.dkr.ecr.us-west-2.amazonaws.com/btc-predictor-function"]
confirm_changeset = false